//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditory
    {
        public int ID_Auditory { get; set; }
        public string Auditory_Number { get; set; }
        public string Status_Name { get; set; }
        public System.DateTime Last_Change_Date { get; set; }
        public int Capasity { get; set; }
        public int Inventory_ID { get; set; }
        public int Sotrudnik_ID { get; set; }
    }
}
