//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Auditory
    {
        public int Код_аудитории { get; set; }
        public string Номер_аудитории { get; set; }
        public int Вместимость { get; set; }
        public string Статус { get; set; }
        public System.DateTime Дата_последнего_изменения { get; set; }
        public string Фамилия_изменившего { get; set; }
        public string Имя_изменившего { get; set; }
        public string Отчество_изменившего { get; set; }
        public string Номер_телефона { get; set; }
        public string Должность { get; set; }
        public string Название_инвентаря { get; set; }
        public string Описание_инвентаря { get; set; }
        public int Количество { get; set; }
    }
}
