USE [master]
GO

/****** Object:  Database [TRPO]    Script Date: 23.04.2023 16:19:19 ******/
CREATE DATABASE [TRPO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TRPO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS01\MSSQL\DATA\TRPO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TRPO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS01\MSSQL\DATA\TRPO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [TRPO] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TRPO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TRPO] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TRPO] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TRPO] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TRPO] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TRPO] SET ARITHABORT OFF 
GO

ALTER DATABASE [TRPO] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TRPO] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TRPO] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TRPO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TRPO] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TRPO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TRPO] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TRPO] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TRPO] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TRPO] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TRPO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TRPO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TRPO] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TRPO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TRPO] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TRPO] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TRPO] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TRPO] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TRPO] SET  MULTI_USER 
GO

ALTER DATABASE [TRPO] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TRPO] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TRPO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TRPO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TRPO] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TRPO] SET QUERY_STORE = OFF
GO

USE [TRPO]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [TRPO] SET  READ_WRITE 
GO

